name: Kernel Build

on:
  workflow_dispatch: # jalan manual dari tab Actions

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permission
        run: chmod +x kernel-build.sh

      - name: Run kernel build script
        run: ./kernel-build.sh
